rm -rf "/Library/Application Support/VMware"
rm -rf "/Library/Application Support/VMware Fusion"
rm -rf "/Library/Preferences/VMware Fusion"
rm -rf "~/Library/Application Support/VMware Fusion"
rm -rf "~/Library/Caches/com.vmware.fusion"
rm -rf "~/Library/Preferences/VMware Fusion"
rm -rf "~/Library/Preferences/com.vmware.fusion.LSSharedFileList.plist"
rm -rf "~/Library/Preferences/com.vmware.fusion.LSSharedFileList.plist.lockfile"
rm -rf "~/Library/Preferences/com.vmware.fusion.plist"
rm -rf "~/Library/Preferences/com.vmware.fusion.plist.lockfile"
rm -rf "~/Library/Preferences/com.vmware.fusionDaemon.plist"
rm -rf "~/Library/Preferences/com.vmware.fusionDaemon.plist.lockfile"
rm -rf "~/Library/Preferences/com.vmware.fusionStartMenu.plist"
rm -rf "~/Library/Preferences/com.vmware.fusionStartMenu.plist.lockfile"